### PR TITLE
Issue #7 - RangedInt - include all indexes in particular dimension

### PR DESCRIPTION
**Pull request by rahulpalamuttam**
~~ is used as a Nil operator, which is mapped to the complete range in the apply function.
I was not able to support the ~ operator as I kept running into compile errors asking me to put { at the end of the ~.

### CODE REVIEW

**Comment by agibsonccc** [comment]
Could you elaborate on the compile errors a bit? @taisukeoe do you think you could chip in on this?

**Comment by rahulpalamuttam** [comment]
Here is the error I was seeing when the test function used '~' instead of ~~

[error] /Users/rahulsp/IdeaProjects/nd4s/src/test/scala/org/nd4j/api/NDArrayExtractionTest.scala:43: illegal start of simple expression
[error]     val extracted = nd(0 ~ 0, ~ , ~)
[error]                                 ^
[error] /Users/rahulsp/IdeaProjects/nd4s/src/test/scala/org/nd4j/api/NDArrayExtractionTest.scala:48: ')' expected but '}' found.
[error]   }
[error]   ^
[error] two errors found

**Comment by taisukeoe** [comment]
`~` cannot be used as a value since there is an unary operator `~` separately in Scala and Scala compiler misunderstands `~` as a start of unary operation and shows error as @rahulpalamuttam shows.

So if we want to use something like `~` value as all-ranged like NumPy, we can do one of the followings:

1. Use `~~` as @rahulpalamuttam suggests.

2. Change `~` to different operator. Let me send another PR for proposal.
https://github.com/deeplearning4j/nd4s/pull/11

**Comment by agibsonccc** [comment]
@taisukeoe The arrow syntax reminds me too much of lambdas.

**Comment by taisukeoe** [comment]
I see your point in Java8. In Scala, it is the syntax to make Tuple2 which stands for a pair of values, not Lambda.
It's a matter of choice, which culture is more familar for users. 

Whichever I'm OK for. I respect your decision.

**Comment by taisukeoe** [comment]
Another funny idea is to use `：` (unicode colon), instead of `:` colon in NumPy :)
Though I'm familiar with unicode colon, I'm not sure for others.

**Comment by agibsonccc** [comment]
Taisuke merge this one then. While in scala land... do as the scala people
do

**Comment by agibsonccc** [comment]
Merged: #11  Credit to rahul for  the fixes!

**Comment by taisukeoe** [comment]
Thanks for your feature suggestion & Agree with the Credit to you, @rahulpalamuttam !

**Pull request closed without merging**
