### PR TITLE
bump up libraries to support scala 2.12

### PR DESCRIPTION
**Pull request by letalvoj**
* remove to while-loop optimization from two cycles to remove legacy dependency
 * add the newest versions of all libraries which still support all Scala 2.10, 2.11, 2.12

If you really find the two for-loops really must be optimized we can rewrite them to while-loops manually.

### CODE REVIEW

**Comment by letalvoj** [comment]
Resolves issue [#108](https://github.com/deeplearning4j/nd4s/issues/108).

**Comment by letalvoj** [comment]
Well, it seems that there is no `dl4j` version `0.9.2-SNAPSHOT`... I can not do anything about it. Changing the default version in the `build.sbt` did not make much sense. I do not know whether you stick to rolling out appropriate version together or what is your policy on this issue.

**Comment by agibsonccc** [comment]
@letalvoj you would have to build from source for that

**Comment by letalvoj** [comment]
Works for me (actually I was lazy and locally used `0.9.1`) but it does not fix the build on Travis. :-(

**Comment by letalvoj** [comment]
I found crazy weird optimizing a loop but still using _exception handling_ to break out of it. Thus I removed the `scala.util.control.Breaks` and used plain old procedural boolean flag.

When you fix the `Complex...` stuff and release the appropriate version of `nd4j-native` the tests should be passing.

Fixes also bug https://github.com/deeplearning4j/nd4s/issues/120

**Comment by huitseeker** [comment]
@letalvoj

**Comment by letalvoj** [comment]
Done ✔️

**Comment by saudet** [comment]
LGTM, so let's merge this so others start can testing it more easily. Thanks!

**Pull request merged**
